Public Class EditarOrdenModel
    Public Property fecha_creacion() As String
    Public Property nombre_cliente() As String
    Public Property nombre_usuario() As String
    Public Property correo_cliente() As String
    Public Property direccion_cliente() As String
    Public Property telefono_cliente() As String
    Public Property numero_orden() As String
    Public Property fecha_entrega() As String
    Public Property tamaño() As String
    Public Property cantidad() As String
    Public Property numero_paginas() As String
    Public Property lugar_entrega() As String
    Public Property prioridad() As String
    Public Property orientacion() As String
    Public Property material_portada() As String
    Public Property gramaje_portada() As String
    Public Property color_portada() As String
    Public Property tamaño_portada() As String
    Public Property material_interior() As String
    Public Property gramaje_interior() As String
    Public Property color_interior() As String
    Public Property tamaño_interior() As String
    Public Property material_otro() As String
    Public Property gramaje_otro() As String
    Public Property color_otro() As String
    Public Property tamaño_otro() As String
    Public Property cantidad_resmas_portada() As String
    Public Property cantidad_resmas_interior() As String
    Public Property cantidad_resmas_otro() As String
    Public Property full_color_portada() As String
    Public Property duotono_portada() As String
    Public Property unicolor_portada() As String
    Public Property pantone_portada() As String
    Public Property cantidad_tinta_portada() As String
    Public Property full_color_interior() As String
    Public Property duotono_interior() As String
    Public Property unicolor_interior() As String
    Public Property pantone_interior() As String
    Public Property cantidad_tinta_interior() As String
    Public Property acabado_de_portada() As String
    Public Property cantidad_acabado_de_portada() As String
    Public Property diseño_diseño() As String
    Public Property diseño_imp_digital() As String
    Public Property diseño_ctp() As String
    Public Property diseño_prensa() As String
    Public Property diseño_reimpresion() As String
    Public Property portada_tiro_retiro() As String
    Public Property portada_tiro() As String
    Public Property interior_tiro_retiro() As String
    Public Property interior_tiro() As String
    Public Property cantidad_imprimir() As String
    Public Property encuadernacion_plegado() As String
    Public Property encuadernacion_pegado() As String
    Public Property encuadernacion_alzado() As String
    Public Property encuadernacion_cortado() As String
    Public Property encuadernacion_perforado() As String
    Public Property encuadernacion_grapado() As String
    Public Property encuadernacion_numerado() As String
    Public Property encuadernacion_empacado() As String
    Public Property observaciones_especificas() As String
    Public Property estado() As String
    Public Property estadoOrden() As String
    Public Property colorPortada() As String
    Public Property colorInterior() As String
    Public Property tiroPortada() As String
    Public Property tiroInterior() As String
    Public Property descripcionTrabajo() As String
End Class
